###
GET http://localhost:8080/book

###
@isbn =978-0201633611834756348756
GET http://localhost:8080/book/{{isbn}}

###
@author=Rob
GET http://localhost:8080/book?author={{author}}

###
POST http://localhost:8080/book/search
Content-Type: application/json

{
  "isbn": "978-0201633610",
  "author": "Rob",
  "other": "something else"
}
