application:
  name: 'Bookshelf'
  title: '@project.name@'
  version: '@project.version@'
  profile: 'Default'

swagger:
  title: "Bookshelf API"
  description: 'Description'
  capacity: 1000
  license:
    name: 'MIT License'
    url: 'http://example.com'

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bookshelf
#    url: jdbc:h2:mem:bookshelf
    username: birgit
    password: geheim
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
#    generate-ddl: true
#    defer-datasource-initialization: true
#  h2:
#    console:
#      enabled: true
  sql:
    init:
      mode: always

  security:
    user:
      name: birgit
      password: geheim

management:
  endpoints:
    web:
      exposure:
        include: "health,liquibase"
